Proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nacionalidad/', include('apps.nacionalidad.urls', namespace="nacionalidad")),

]

apps/nacionalidad/urls.py
from django.conf.urls import url
from apps.nacionalidad.views import index, nacionalidad_view

urlpatterns = [
    url(r'^index$', index, name='index'),
    url(r'^nuevo$',nacionalidad_view, name='nueva_nacionalidad'),
    url(r'^nacionalidad/nuevo$',nacionalidad_view, name='nueva_nacionalidad'),

]

apps/nacionalidad/models.py
from django.db import models

# Create your models here.
class Nacionalidad(models.Model):
    #codigo = models.AutoField(primary_key= True)
    #django te crea un id autoincrementable.

    nombre = models.CharField(max_length=50)
    habilitado = models.BooleanField(default = True)

    class Meta:
        verbose_name_plural = "nacionalidades"
class Persona(models.Model):
    nombre = models.CharField(max_length=50)

class Animal(models.Model):
    nombre = models.CharField(max_length=50)

apps/nacionalidad/forms.py
from django import forms
from apps.nacionalidad.models import Nacionalidad

class NacionalidadForm(forms.Form):
    nombre = forms.CharField(max_length=100, required=True),
    descripcion = forms.CharField(max_length=100, required=True),

    class Meta:

        model = Nacionalidad


        #campos a utilizar del modelo
        fields = [
            'nombre',
            'habilitado',
        ]


        #etiquetas en el formulario
        labels = {
            'nombre': 'Nombre',
            'habilitado': 'Habilitado',
        }


        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'habilitado': forms.TextInput(attrs={'class':'form-control'}),
        }

apps/nacionalidad/views.py
from django.shortcuts import render,redirect
from django.http import  HttpResponse
from apps.nacionalidad.forms import NacionalidadForm
from django.views.generic import ListView, CreateView
from apps.nacionalidad.models import Nacionalidad
# Create your views here.

def index(request):
    #return HttpResponse("LLego hasta el index")
    return render(request,'nacionalidad/index.html')


def nacionalidad_view(request):
    if request.method == 'POST':
        form = NacionalidadForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('nacionalidad:index')
    else:
        form = NacionalidadForm()
    return render(request, 'nacionalidad/nacionalidad_form.html',{'form':form})



class NacionalidadCreate(CreateView):
    model = Nacionalidad
    template_name = 'nacionalidad/nacionalidad_form.html'

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% block extrastatic %}

    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <title>{% block title%}Document {% endblock %}</title>
</head>
<body>
<div class="container">

    {% block navbar %}
    <div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Personas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'nacionalidad:nueva_nacionalidad' %}">Registrar</a></li>
                                            <li><a href="#">Listar</a></li>

                                        </ul>
		                      		</li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
    </div>
    {% endblock %}

</div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}



</body>
</html>

templates/nacionalidad/index.html
{% extends 'base/base.html'%}

{% block title%}
Nacionalidad
{% endblock %}

templates/nacionalidad/nacionalidad_form.html
{% extends 'base/base.html' %}

{% block content %}
 <form method="POST">
     <h1>New post</h1>
     {% csrf_token %}
     {{ form.as_p }}

    <button type="submit">Guardar</button>
 </form>
{% endblock %}